name: Deploy to Oracle Cloud

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Oracle Server
        env:
          USER: ubuntu             
          HOST: 158.180.17.176 
          REMOTE_PATH: /var/www/html   
        run: |
          rsync -avz --delete ./ $USER@$HOST:$REMOTE_PATH
          ssh $USER@$HOST "sudo systemctl restart apache2"
