name: Deploy to Oracle Cloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy to Oracle Server
        env:
          USER: ubuntu
          HOST: 158.180.17.176
          REMOTE_PATH: /var/www/html
        run: |
          rsync -avz -e "ssh -o StrictHostKeyChecking=no" --delete ${{ github.workspace }}/dist/ $USER@$HOST:$REMOTE_PATH
          ssh -o StrictHostKeyChecking=no $USER@$HOST "sudo systemctl restart apache2"

      - name: Verify Deployment
        env:
          USER: ubuntu
          HOST: 158.180.17.176
          REMOTE_PATH: /var/www/html
        run: |
          ssh $USER@$HOST "ls -la $REMOTE_PATH"
